title: blog da Vic
description: > # this means to ignore newlines until "baseurl:"
  Oi, tudo bom? Esse é o meu espaço para compartilhar sobre temas que me interessam. 
  Geralmente eu escrevo sobre aprendizagem. Às vezes aprendizagem de gente. Às vezes aprendizagem de máquina.
permalink: ':Vic Santiago/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victoriasantiago.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Victória Santiago # add your name
author-img: "vic-santiago.png" # add your photo
about-author:  Desenvolvedora de software. Estudante de Machine Learning.       Entusiasta de aprendizagem livre.
 # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: victoriasantiago # add your Github handle
social-linkedin: victóriasantiago # add your Linkedin handle
social-email: vsantiago18@hotmail.com # add your Email address

# Disqus
discus-identifier: vicsantiago18 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
include: ["_posts"]